name: test
on: push
jobs:
   job1:
    name: test1
    runs-on: ubuntu:latest
    steps:
    - name: checkout
      run: date
   job2: 
    name: test2
    needs: [job1]
    runs-on: windows-latest
    steps:
    - name: checkout
      run: date
